services:
  - type: web
    name: pendel-simulator
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      npm --prefix frontend install
      npm --prefix frontend run build
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    healthCheckPath: /
